import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/client/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-900 text-slate-100 pt-16 min-h-screen`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
